from enum import Enum
from typing import List, Optional, Any, Dict
from pydantic import BaseModel, Field
from backend.models.common import get_current_iso_time


class InsightType(str, Enum):
    SHARED_ENTITY = "SHARED_ENTITY"
    CROSS_CASE_LINK = "CROSS_CASE_LINK"
    BRIDGE_NODE = "BRIDGE_NODE"
    TRANSFER_CHAIN = "TRANSFER_CHAIN"
    HIGH_FAN_IN = "HIGH_FAN_IN"
    HIGH_FAN_OUT = "HIGH_FAN_OUT"
    INFRASTRUCTURE_REUSE = "INFRASTRUCTURE_REUSE"
    POSSIBLE_CO_LOCATION = "POSSIBLE_CO_LOCATION"
    CROSS_DOMAIN_PATH = "CROSS_DOMAIN_PATH"
    PRIOR_CASE_LINK = "PRIOR_CASE_LINK"


class InsightSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class InsightItem(BaseModel):
    insight_id: str = Field(..., description="Unique deterministic or generated insight ID")
    insight_type: InsightType = Field(..., description="Canonical category of the insight")
    title: str = Field(..., description="Concise title summarizing the insight")
    severity: InsightSeverity = Field(default=InsightSeverity.MEDIUM, description="Investigative severity level")
    observed_facts: List[str] = Field(..., description="Objective facts observed directly in graph data")
    derived_interpretation: str = Field(..., description="Analytical inference or hypothesis")
    alternative_explanations: List[str] = Field(default_factory=list, description="Plausible benign or alternate explanations")
    disclaimer: str = Field(
        default="Generated for investigative assistance only; requires independent verification.",
        description="Standard legal / investigative disclaimer"
    )
    entities_involved: List[str] = Field(default_factory=list, description="IDs of entities participating in pattern")
    case_ids: List[str] = Field(default_factory=list, description="Related case identifiers")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional context or metrics")
    created_at: str = Field(default_factory=get_current_iso_time, description="Creation timestamp")


class CaseAIInsightResponse(BaseModel):
    case_id: str = Field(..., description="Target case ID")
    case_name: str = Field(default="", description="Case name or title")
    status: str = Field(default="OPEN", description="Case status")
    risk_level: str = Field(default="HIGH", description="AI assessed risk level")
    executive_summary: str = Field(..., description="Executive intelligence brief generated by Gemini")
    modus_operandi: str = Field(default="", description="Reconstructed modus operandi")
    key_suspects: List[str] = Field(default_factory=list, description="Primary suspects and operators identified")
    critical_anomalies: List[str] = Field(default_factory=list, description="Key red flags and transaction anomalies")
    investigative_leads: List[str] = Field(default_factory=list, description="Actionable next steps, search warrants, wiretaps")
    ai_model: str = Field(default="gemini-2.5-flash", description="Underlying Gemini model")
    generated_at: str = Field(default_factory=get_current_iso_time, description="Generation timestamp")


class GraphAIChatRequest(BaseModel):
    question: str = Field(..., description="User question about the graph network")
    case_id: Optional[str] = Field(default=None, description="Current case identifier or empty for all cases")
    nodes_count: Optional[int] = Field(default=None, description="Number of nodes currently in view")
    edges_count: Optional[int] = Field(default=None, description="Number of edges currently in view")
    selected_node_id: Optional[str] = Field(default=None, description="Optional focused entity ID")


class GraphAIChatResponse(BaseModel):
    answer: str = Field(..., description="AI investigative response to the question")
    key_findings: List[str] = Field(default_factory=list, description="Key extracted entity names or bullet points")
    extracted_graph_type: Optional[str] = Field(default=None, description="Active extracted subgraph mode: cdr, person, financial, or all")
    ai_model: str = Field(default="gemini-2.5-flash", description="AI model used for response")
    generated_at: str = Field(default_factory=get_current_iso_time, description="Timestamp of generation")



